### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by foxhound87** [mikeerickson/validatorjs#126]
**Uncaught (in promise) TypeError: Cannot read property 'length' of null**

I cannot get rid of this error, I don't know if it's my mistake.
I'm not using async functionalities of validatorjs in the executed code.

Below you can see the error stack and a block of code at the end with the line of the error.

thank you.

```
 at Validator._parseRules (eval at <anonymous> (http://localhost:8888/main.js:1157:2), <anonymous>:227:39)
    at new Validator (eval at <anonymous> (http://localhost:8888/main.js:1157:2), <anonymous>:19:21)
    at DVR.validateField (eval at <anonymous> (http://localhost:8888/main.js:1313:2), <anonymous>:81:26)
    at Validator.validateField (eval at <anonymous> (http://localhost:8888/main.js:1289:2), <anonymous>:227:22)
    at eval (eval at <anonymous> (http://localhost:8888/main.js:1289:2), <anonymous>:206:24)
    at eval (eval at <anonymous> (http://localhost:8888/main.js:1109:2), <anonymous>:4738:15)
    at baseForOwn (eval at <anonymous> (http://localhost:8888/main.js:1109:2), <anonymous>:2879:24)
    at eval (eval at <anonymous> (http://localhost:8888/main.js:1109:2), <anonymous>:4707:18)
    at Function.forEach (eval at <anonymous> (http://localhost:8888/main.js:1109:2), <anonymous>:9011:14)
    at Validator.validateAll (eval at <anonymous> (http://localhost:8888/main.js:1289:2), <anonymous>:205:26)
```

```
_parseRules @   validator.js?76f7:227
Validator   @   validator.js?76f7:19
validateField   @   DVR.js?aace:34
validateField   @   Validator.js?f0c6:98
(anonymous function)    @   Validator.js?f0c6:86
(anonymous function)    @   lodash.js?03cc:4738
baseForOwn  @   lodash.js?03cc:2879
(anonymous function)    @   lodash.js?03cc:4707
forEach @   lodash.js?03cc:9011
validateAll @   Validator.js?f0c6:85
executeAction   @   mobx.js?6a62:592
res @   mobx.js?6a62:564
(anonymous function)    @   Form.js?dc6a:78
validate    @   Form.js?dc6a:76
Form    @   Form.js?dc6a:30
Form    @   VM217246:35
RegisterForm    @   VM217236:58
(anonymous function)    @   _.forms.js?d21b:26
(anonymous function)    @   main.js:1145
__webpack_require__ @   main.js:20
(anonymous function)    @   Main.jsx?8b73:9
(anonymous function)    @   main.js:1079
__webpack_require__ @   main.js:20
(anonymous function)    @   main.jsx?0d59:3
(anonymous function)    @   main.js:47
__webpack_require__ @   main.js:20
(anonymous function)    @   main.js:40
(anonymous function)    @   main.js:43
```

**_parseRules    @ validator.js?76f7:227**

```
      if (typeof rulesArray === 'string') {
        rulesArray = rulesArray.split('|');
      }

      for (var i = 0, len = rulesArray.length, rule; i < len; i++) { <<<<<<<<<<<<<<<<<<<<<<<<<
        rule = this._extractRuleAndRuleValue(rulesArray[i]);
        if (Rules.isAsync(rule.name)) {
          this.hasAsync = true;
        }
        attributeRules.push(rule);
      }
```

**Comment by foxhound87** [comment]
The error was thrown if I don't specify a rule for some fields.
